### ISSUE TITLE
Error: could not assemble transaction, err proposal response was not successful, error code 500, msg error starting container: error starting container: cannot connect to Docker endpoint

### ISSUE THREAD

**Issue by myishuohuo** [IBM/blockchain-network-on-kubernetes#64]
When I deployed on the k8s，I see Error: could not assemble transaction, err proposal response was not successful, error code 500, msg error starting container: error starting container: cannot connect to Docker endpoint
![image](https://user-images.githubusercontent.com/31065623/77757064-741b9e00-706b-11ea-8fc7-9eb2203a54ea.png)
![image](https://user-images.githubusercontent.com/31065623/77757098-88f83180-706b-11ea-90c0-cd71e73f3703.png)

**Comment by maheshwarishikha** [comment]
@myishuohuo - Please take the latest code and retry. I have updated the code repository for the Kubernetes 1.16. It should work now. Thanks.

**Comment by maheshwarishikha** [comment]
@myishuohuo - Hope it has worked for you. Closing the issue because of no activity. Feel free to reopen or open a new issue if required. Thanks.

**Comment by Delagrace** [comment]
i am on deploying the network on IBM cloud kubernetes service with kubernetes v1.27.12. still facing the same error during instantiation : Error: could not assemble transaction, err proposal response was not successful, error code 500, msg error starting container: error starting container: cannot connect to Docker endpoint
